export const PERSON_ORDER = ["Eu", "Tu", "Ele/Ela/Você", "Nós", "Vós", "Eles/Elas/Vocês"];
export const TENSE_ORDER = ["Presente", "Pretérito Perfeito", "Pretérito Imperfeito", "Futuro", "Condicional", "Conjuntivo"];

const FUT_ENDINGS = ["ei", "ás", "á", "emos", "eis", "ão"];
const COND_ENDINGS = ["ia", "ias", "ia", "íamos", "íeis", "iam"];

function makeRegularVerb(infinitive: string, meaning: string) {
  const lower = infinitive.toLowerCase();
  const ending = lower.slice(-2);
  const stem = lower.slice(0, -2);
  
  const endings: any = {
    ar: { pres: ["o", "as", "a", "amos", "ais", "am"], perf: ["ei", "aste", "ou", "amos", "astes", "aram"], imp: ["ava", "avas", "ava", "ávamos", "áveis", "avam"], conj: ["e", "es", "e", "emos", "eis", "em"] },
    er: { pres: ["o", "es", "e", "emos", "eis", "em"], perf: ["i", "este", "eu", "emos", "estes", "eram"], imp: ["ia", "ias", "ia", "íamos", "íeis", "iam"], conj: ["a", "as", "a", "amos", "ais", "am"] },
    ir: { pres: ["o", "es", "e", "imos", "is", "em"], perf: ["i", "iste", "iu", "imos", "istes", "iram"], imp: ["ia", "ias", "ia", "íamos", "íeis", "iam"], conj: ["a", "as", "a", "amos", "ais", "am"] }
  };

  const e = endings[ending] || endings.ar;
  const m = meaning.replace("to ", "");

  return {
    meaning,
    tenses: {
      "Presente": { forms: PERSON_ORDER.map((_, i) => stem + e.pres[i]), sentence: { pt: `Eu ${stem + e.pres[0]} todos os dias.`, en: `I ${m} every day.` }},
      "Pretérito Perfeito": { forms: PERSON_ORDER.map((_, i) => stem + e.perf[i]), sentence: { pt: `Ontem eu ${stem + e.perf[0]}.`, en: `Yesterday I ${m}.` }},
      "Pretérito Imperfeito": { forms: PERSON_ORDER.map((_, i) => stem + e.imp[i]), sentence: { pt: `Antes eu ${stem + e.imp[0]} mais.`, en: `Before, I used to ${m} more.` }},
      "Futuro": { forms: PERSON_ORDER.map((_, i) => lower + FUT_ENDINGS[i]), sentence: { pt: `Amanhã eu ${lower + FUT_ENDINGS[0]}.`, en: `Tomorrow I will ${m}.` }},
      "Condicional": { forms: PERSON_ORDER.map((_, i) => lower + COND_ENDINGS[i]), sentence: { pt: `Eu ${lower + COND_ENDINGS[0]} se pudesse.`, en: `I would ${m} if I could.` }},
      "Conjuntivo": { forms: PERSON_ORDER.map((_, i) => stem + e.conj[i]), sentence: { pt: `Espero que eu ${stem + e.conj[0]} bem.`, en: `I hope that I ${m} well.` }}
    }
  };
}

export const VERB_BANK: any = {
  "Ser": { meaning: "to be (permanent)", tenses: { "Presente": { forms: ["sou","és","é","somos","sois","são"], sentence: {pt:"Eu sou feliz.", en:"I am happy."}}, "Pretérito Perfeito": { forms: ["fui","foste","foi","fomos","fostes","foram"], sentence: {pt:"Eu fui ao Brasil.", en:"I went to Brazil."}}, "Pretérito Imperfeito": { forms: ["era","eras","era","éramos","éreis","eram"], sentence: {pt:"Eu era jovem.", en:"I was young."}}, "Futuro": { forms: ["serei","serás","será","seremos","sereis","serão"], sentence: {pt:"Serei pontual.", en:"I will be punctual."}}, "Condicional": { forms: ["seria","serias","seria","seríamos","seríeis","seriam"], sentence: {pt:"Seria ótimo!", en:"It would be great!"}}, "Conjuntivo": { forms: ["seja","sejas","seja","sejamos","sejais","sejam"], sentence: {pt:"Espero que seja bom.", en:"I hope it's good."}}}},
  "Estar": { meaning: "to be (temp)", tenses: { "Presente": { forms: ["estou","estás","está","estamos","estais","estão"], sentence: {pt:"Estou em casa.", en:"I'm home."}}, "Pretérito Perfeito": { forms: ["estive","estiveste","esteve","estivemos","estivestes","estiveram"], sentence: {pt:"Eu estive lá.", en:"I was there."}}, "Pretérito Imperfeito": { forms: ["estava","estavas","estava","estávamos","estáveis","estavam"], sentence: {pt:"Eu estava cansado.", en:"I was tired."}}, "Futuro": { forms: ["estarei","estarás","estará","estaremos","estareis","estarão"], sentence: {pt:"Estarei livre.", en:"I'll be free."}}, "Condicional": { forms: ["estaria","estarias","estaria","estaríamos","estaríeis","estariam"], sentence: {pt:"Eu estaria lá.", en:"I would be there."}}, "Conjuntivo": { forms: ["esteja","estejas","esteja","estejamos","estejais","estejam"], sentence: {pt:"Espero que esteja bem.", en:"I hope it's okay."}}}},
  "Ir": { meaning: "to go", tenses: { "Presente": { forms: ["vou","vais","vai","vamos","ides","vão"], sentence: {pt:"Eu vou agora.", en:"I go now."}}, "Pretérito Perfeito": { forms: ["fui","foste","foi","fomos","fostes","foram"], sentence: {pt:"Eu fui ontem.", en:"I went yesterday."}}, "Pretérito Imperfeito": { forms: ["ia","ias","ia","íamos","íeis","iam"], sentence: {pt:"Eu ia sempre.", en:"I used to go always."}}, "Futuro": { forms: ["irei","irás","irá","iremos","ireis","irão"], sentence: {pt:"Irei amanhã.", en:"I will go tomorrow."}}, "Condicional": { forms: ["iria","irias","iria","iríamos","iríeis","iriam"], sentence: {pt:"Eu iria com você.", en:"I would go with you."}}, "Conjuntivo": { forms: ["vá","vás","vá","vamos","vades","vão"], sentence: {pt:"Que tudo vá bem.", en:"May everything go well."}}}},
  "Ter": { meaning: "to have", tenses: { "Presente": { forms: ["tenho","tens","tem","temos","tendes","têm"], sentence: {pt:"Tenho um plano.", en:"I have a plan."}}, "Pretérito Perfeito": { forms: ["tive","tiveste","teve","tivemos","tivestes","tiveram"], sentence: {pt:"Tive uma ideia.", en:"I had an idea."}}, "Pretérito Imperfeito": { forms: ["tinha","tinhas","tinha","tínhamos","tínheis","tinham"], sentence: {pt:"Eu tinha um gato.", en:"I had a cat."}}, "Futuro": { forms: ["terei","terás","terá","teremos","tereis","terão"], sentence: {pt:"Terei tempo.", en:"I'll have time."}}, "Condicional": { forms: ["teria","terias","teria","teríamos","teríeis","teriam"], sentence: {pt:"Teria sido bom.", en:"It would've been good."}}, "Conjuntivo": { forms: ["tenha","tenhas","tenha","tenhamos","tenhais","tenham"], sentence: {pt:"Espero que tenha.", en:"I hope you have it."}}}},
  "Fazer": { meaning: "to do/make", tenses: { "Presente": { forms: ["faço","fazes","faz","fazemos","fazeis","fazem"], sentence: {pt:"Eu faço café.", en:"I make coffee."}}, "Pretérito Perfeito": { forms: ["fiz","fizeste","fez","fizemos","fizestes","fizeram"], sentence: {pt:"Eu fiz as malas.", en:"I packed."}}, "Pretérito Imperfeito": { forms: ["fazia","fazias","fazia","fazíamos","fazíeis","faziam"], sentence: {pt:"Eu fazia desporto.", en:"I used to do sports."}}, "Futuro": { forms: ["farei","farás","fará","faremos","fareis","farão"], sentence: {pt:"Farei o bolo.", en:"I'll make the cake."}}, "Condicional": { forms: ["faria","farias","faria","faríamos","faríeis","fariam"], sentence: {pt:"Eu faria tudo.", en:"I would do everything."}}, "Conjuntivo": { forms: ["faça","faças","faça","façamos","façais","façam"], sentence: {pt:"Faça o que quiser.", en:"Do what you want."}}}},
  "Poder": { meaning: "can/to be able", tenses: { "Presente": { forms: ["posso","podes","pode","podemos","podeis","podem"], sentence: {pt:"Eu posso ir.", en:"I can go."}}, "Pretérito Perfeito": { forms: ["pude","pudeste","pôde","pudemos","pudestes","puderam"], sentence: {pt:"Não pude vir.", en:"I couldn't come."}}, "Pretérito Imperfeito": { forms: ["podia","podias","podia","podíamos","podíeis","podiam"], sentence: {pt:"Eu podia ler.", en:"I could read."}}, "Futuro": { forms: ["poderei","poderás","poderá","poderemos","podereis","poderão"], sentence: {pt:"Poderei ajudar.", en:"I'll be able to help."}}, "Condicional": { forms: ["poderia","poderias","poderia","poderíamos","poderíeis","poderiam"], sentence: {pt:"Eu poderia tentar.", en:"I could try."}}, "Conjuntivo": { forms: ["possa","possas","possa","possamos","possais","possam"], sentence: {pt:"Espero que possa.", en:"I hope you can."}}}},
  "Dizer": { meaning: "to say", tenses: { "Presente": { forms: ["digo","dizes","diz","dizemos","dizeis","dizem"], sentence: {pt:"Eu digo a verdade.", en:"I tell the truth."}}, "Pretérito Perfeito": { forms: ["disse","disseste","disse","dissemos","dissestes","disseram"], sentence: {pt:"Eu disse 'oi'.", en:"I said 'hi'."}}, "Pretérito Imperfeito": { forms: ["dizia","dizias","dizia","dizíamos","dizíeis","diziam"], sentence: {pt:"Ela dizia que sim.", en:"She used to say yes."}}, "Futuro": { forms: ["direi","dirás","dirá","diremos","direis","dirão"], sentence: {pt:"Eu direi o plano.", en:"I will say the plan."}}, "Condicional": { forms: ["diria","dirias","diria","diríamos","diríeis","diriam"], sentence: {pt:"Eu diria nada.", en:"I would say nothing."}}, "Conjuntivo": { forms: ["diga","digas","diga","digamos","digais","digam"], sentence: {pt:"Diga-me algo.", en:"Tell me something."}}}},
  "Saber": { meaning: "to know (facts)", tenses: { "Presente": { forms: ["sei","sabes","sabe","sabemos","sabeis","sabem"], sentence: {pt:"Eu sei tudo.", en:"I know everything."}}, "Pretérito Perfeito": { forms: ["soube","soubeste","soube","soubemos","soubestes","souberam"], sentence: {pt:"Eu soube logo.", en:"I knew right away."}}, "Pretérito Imperfeito": { forms: ["sabia","sabias","sabia","sabíamos","sabíeis","sabiam"], sentence: {pt:"Eu sabia o nome.", en:"I knew the name."}}, "Futuro": { forms: ["saberei","saberás","saberá","saberemos","sabereis","saberão"], sentence: {pt:"Saberei em breve.", en:"I will know soon."}}, "Condicional": { forms: ["saberia","saberias","saberia","saberíamos","saberíeis","saberiam"], sentence: {pt:"Eu saberia responder.", en:"I would know how to answer."}}, "Conjuntivo": { forms: ["saiba","saibas","saiba","saibamos","saibais","saibam"], sentence: {pt:"Espero que saiba.", en:"I hope you know."}}}},
  "Ver": { meaning: "to see", tenses: { "Presente": { forms: ["vejo","vês","vê","vemos","vedes","veem"], sentence: {pt:"Eu vejo você.", en:"I see you."}}, "Pretérito Perfeito": { forms: ["vi","viste","viu","vimos","vistes","viram"], sentence: {pt:"Eu vi o filme.", en:"I saw the movie."}}, "Pretérito Imperfeito": { forms: ["via","vias","via","víamos","víeis","viam"], sentence: {pt:"Eu via o mar.", en:"I used to see the sea."}}, "Futuro": { forms: ["verei","verás","verá","veremos","vereis","verão"], sentence: {pt:"Eu verei o resultado.", en:"I will see the result."}}, "Condicional": { forms: ["veria","verias","veria","veríamos","veríeis","veriam"], sentence: {pt:"Eu veria de novo.", en:"I would see it again."}}, "Conjuntivo": { forms: ["veja","vejas","veja","vejamos","vejais","vejam"], sentence: {pt:"Veja bem.", en:"Look closely."}}}},
  "Dar": { meaning: "to give", tenses: { "Presente": { forms: ["dou","dás","dá","damos","dais","dão"], sentence: {pt:"Eu dou um abraço.", en:"I give a hug."}}, "Pretérito Perfeito": { forms: ["dei","deste","deu","demos","destes","deram"], sentence: {pt:"Eu dei um livro.", en:"I gave a book."}}, "Pretérito Imperfeito": { forms: ["dava","davas","dava","dávamos","dáveis","davam"], sentence: {pt:"Eu dava gorjeta.", en:"I used to give tips."}}, "Futuro": { forms: ["darei","darás","dará","daremos","dareis","darão"], sentence: {pt:"Eu darei apoio.", en:"I will give support."}}, "Condicional": { forms: ["daria","darias","daria","daríamos","daríeis","dariam"], sentence: {pt:"Eu daria a vida.", en:"I would give my life."}}, "Conjuntivo": { forms: ["dê","dês","dê","demos","deis","deem"], sentence: {pt:"Que Deus lhe dê.", en:"May God give you."}}}},
  "Querer": { meaning: "to want", tenses: { "Presente": { forms: ["quero","queres","quer","queremos","quereis","querem"], sentence: {pt:"Quero viajar.", en:"I want to travel."}}, "Pretérito Perfeito": { forms: ["quis","quiseste","quis","quisemos","quisestes","quiseram"], sentence: {pt:"Quis o destino.", en:"Destiny wanted it."}}, "Pretérito Imperfeito": { forms: ["queria","querias","queria","queríamos","queríeis","queriam"], sentence: {pt:"Eu queria ir.", en:"I wanted to go."}}, "Futuro": { forms: ["quererei","quererás","quererá","quereremos","querereis","quererão"], sentence: {pt:"Quererei mais.", en:"I will want more."}}, "Condicional": { forms: ["quereria","quererias","quereria","quereríamos","quereríeis","quereriam"], sentence: {pt:"Eu quereria tentar.", en:"I would want to try."}}, "Conjuntivo": { forms: ["queira","queiras","queira","queiramos","queirais","queiram"], sentence: {pt:"Seja como Deus queira.", en:"As God wills."}}}},
  "Pôr": { meaning: "to put", tenses: { "Presente": { forms: ["ponho","pões","põe","pomos","pondes","põem"], sentence: {pt:"Eu ponho o prato.", en:"I put the plate."}}, "Pretérito Perfeito": { forms: ["pus","puseste","pôs","pusemos","pusestes","puseram"], sentence: {pt:"Eu pus no bolso.", en:"I put it in my pocket."}}, "Pretérito Imperfeito": { forms: ["punha","punhas","punha","púnhamos","púnheis","punham"], sentence: {pt:"Eu punha a mesa.", en:"I used to set the table."}}, "Futuro": { forms: ["porei","porás","porá","poremos","poreis","porão"], sentence: {pt:"Eu porei aqui.", en:"I will put it here."}}, "Condicional": { forms: ["poria","porias","poria","poríamos","poríeis","poriam"], sentence: {pt:"Eu poria ordem.", en:"I would put order."}}, "Conjuntivo": { forms: ["ponha","ponhas","ponha","ponhamos","ponhais","ponham"], sentence: {pt:"Ponha isto lá.", en:"Put this there."}}}},
  "Ler": { meaning: "to read", tenses: { "Presente": { forms: ["leio","lês","lê","lemos","ledes","leem"], sentence: {pt:"Eu leio muito.", en:"I read a lot."}}, "Pretérito Perfeito": { forms: ["li","leste","leu","lemos","lestes","leram"], sentence: {pt:"Eu li o livro.", en:"I read the book."}}, "Pretérito Imperfeito": { forms: ["lia","lias","lia","líamos","líeis","liam"], sentence: {pt:"Eu lia gibis.", en:"I used to read comics."}}, "Futuro": { forms: ["lerei","lerás","lerá","leremos","lereis","lerão"], sentence: {pt:"Eu lerei amanhã.", en:"I will read tomorrow."}}, "Condicional": { forms: ["leria","lerias","leria","leríamos","leríeis","leriam"], sentence: {pt:"Eu leria mais.", en:"I would read more."}}, "Conjuntivo": { forms: ["leia","leias","leia","leiamos","leiais","leiam"], sentence: {pt:"Leia isto.", en:"Read this."}}}},
  "Vir": { meaning: "to come", tenses: { "Presente": { forms: ["venho","vens","vem","vimos","vindes","vêm"], sentence: {pt:"Venho de casa.", en:"I come from home."}}, "Pretérito Perfeito": { forms: ["vim","vieste","veio","viemos","viestes","vieram"], sentence: {pt:"Eu vim sozinho.", en:"I came alone."}}, "Pretérito Imperfeito": { forms: ["vinha","vinhas","vinha","vínhamos","vínheis","vinham"], sentence: {pt:"Eu vinha aqui.", en:"I used to come here."}}, "Futuro": { forms: ["virei","virás","virá","viremos","vireis","virão"], sentence: {pt:"Eu virei amanhã.", en:"I will come tomorrow."}}, "Condicional": { forms: ["viria","virias","viria","viríamos","viríeis","viriam"], sentence: {pt:"Ele viria se pudesse.", en:"He would come if he could."}}, "Conjuntivo": { forms: ["venha","venhas","venha","venhamos","venhais","venham"], sentence: {pt:"Venha aqui.", en:"Come here."}}}},
  "Trazer": { meaning: "to bring", tenses: { "Presente": { forms: ["trago","trazes","traz","trazemos","trazeis","trazem"], sentence: {pt:"Eu trago comida.", en:"I bring food."}}, "Pretérito Perfeito": { forms: ["trouxe","trouxeste","trouxe","trouxemos","trouxestes","trouxeram"], sentence: {pt:"Eu trouxe flores.", en:"I brought flowers."}}, "Pretérito Imperfeito": { forms: ["trazia","trazias","trazia","trazíamos","trazíeis","traziam"], sentence: {pt:"Eu trazia pão.", en:"I used to bring bread."}}, "Futuro": { forms: ["trarei","trarás","trará","traremos","trareis","trarão"], sentence: {pt:"Eu trarei o vinho.", en:"I will bring the wine."}}, "Condicional": { forms: ["traria","trarias","traria","traríamos","traríeis","trariam"], sentence: {pt:"Eu traria ajuda.", en:"I would bring help."}}, "Conjuntivo": { forms: ["traga","tragas","traga","tragamos","tragais","tragam"], sentence: {pt:"Traga o livro.", en:"Bring the book."}}}},
  "Ouvir": { meaning: "to hear", tenses: { "Presente": { forms: ["ouço","ouves","ouve","ouvimos","ouvis","ouvem"], sentence: {pt:"Eu ouço rádio.", en:"I hear the radio."}}, "Pretérito Perfeito": { forms: ["ouvi","ouviste","ouviu","ouvimos","ouvistes","ouviram"], sentence: {pt:"Eu ouvi tudo.", en:"I heard everything."}}, "Pretérito Imperfeito": { forms: ["ouvia","ouvias","ouvia","ouvíamos","ouvíeis","ouviam"], sentence: {pt:"Eu ouvia música.", en:"I used to hear music."}}, "Futuro": { forms: ["ouvirei","ouvirás","ouvirá","ouviremos","ouvireis","ouvirão"], sentence: {pt:"Eu ouvirei você.", en:"I will hear you."}}, "Condicional": { forms: ["ouviria","ouvirias","ouviria","ouviríamos","ouviríeis","ouviriam"], sentence: {pt:"Eu ouviria de novo.", en:"I would hear it again."}}, "Conjuntivo": { forms: ["ouça","ouças","ouça","ouçamos","ouçais","ouçam"], sentence: {pt:"Ouça-me.", en:"Listen to me."}}}},
  "Sair": { meaning: "to leave", tenses: { "Presente": { forms: ["saio","sais","sai","saímos","saís","saem"], sentence: {pt:"Eu saio agora.", en:"I leave now."}}, "Pretérito Perfeito": { forms: ["saí","saíste","saiu","saímos","saístes","saíram"], sentence: {pt:"Eu saí ontem.", en:"I left yesterday."}}, "Pretérito Imperfeito": { forms: ["saía","saías","saía","saíamos","saíeis","saíam"], sentence: {pt:"Eu saía tarde.", en:"I used to leave late."}}, "Futuro": { forms: ["sairei","sairás","sairá","sairemos","saireis","sairão"], sentence: {pt:"Sairei logo.", en:"I will leave soon."}}, "Condicional": { forms: ["sairia","sairias","sairia","sairíamos","sairíeis","sairiam"], sentence: {pt:"Eu sairia com ela.", en:"I would go out with her."}}, "Conjuntivo": { forms: ["saia","saias","saia","saiamos","saiais","saiam"], sentence: {pt:"Saia daqui.", en:"Get out of here."}}}},
  "Pedir": { meaning: "to ask for", tenses: { "Presente": { forms: ["peço","pedes","pede","pedimos","pedis","pedem"], sentence: {pt:"Eu peço café.", en:"I ask for coffee."}}, "Pretérito Perfeito": { forms: ["pedi","pediste","pediu","pedimos","pedistes","pediram"], sentence: {pt:"Eu pedi ajuda.", en:"I asked for help."}}, "Pretérito Imperfeito": { forms: ["pedia","pedias","pedia","pedíamos","pedíeis","pediam"], sentence: {pt:"Eu pedia muito.", en:"I used to ask a lot."}}, "Futuro": { forms: ["pedirei","pedirás","pedirá","pediremos","pedireis","pedirão"], sentence: {pt:"Pedirei pizza.", en:"I will ask for pizza."}}, "Condicional": { forms: ["pediria","pedirias","pediria","pediríamos","pediríeis","pediriam"], sentence: {pt:"Eu pediria desculpas.", en:"I would ask for an apology."}}, "Conjuntivo": { forms: ["peça","peças","peça","peçamos","peçais","peçam"], sentence: {pt:"Peça licença.", en:"Ask for permission."}}}}
};

// --- THE FULL REGULAR LIST (82 More to hit 100) ---
[
  ["Falar", "to speak"], ["Comer", "to eat"], ["Beber", "to drink"], ["Trabalhar", "to work"], ["Estudar", "to study"], 
  ["Morar", "to live"], ["Abrir", "to open"], ["Fechar", "to close"], ["Comprar", "to buy"], ["Vender", "to sell"], 
  ["Gostar", "to like"], ["Dormir", "to sleep"], ["Correr", "to run"], ["Andar", "to walk"], ["Chegar", "to arrive"], 
  ["Passar", "to pass"], ["Ficar", "to stay"], ["Deixar", "to leave"], ["Achar", "to think"], ["Pensar", "to think"], 
  ["Precisar", "to need"], ["Amar", "to love"], ["Chamar", "to call"], ["Olhar", "to look"], ["Escrever", "to write"], 
  ["Responder", "to answer"], ["Entrar", "to enter"], ["Ajudar", "to help"], ["Aprender", "to learn"], ["Assistir", "to watch"], 
  ["Cantar", "to sing"], ["Cozinhar", "to cook"], ["Dançar", "to dance"], ["Decidir", "to decide"], ["Descansar", "to rest"], 
  ["Desenhar", "to draw"], ["Dirigir", "to drive"], ["Escolher", "to choose"], ["Esperar", "to wait"], ["Esquecer", "to forget"], 
  ["Ganhar", "to win"], ["Lavar", "to wash"], ["Limpar", "to clean"], ["Mandar", "to send"], ["Mudar", "to change"], 
  ["Nadar", "to swim"], ["Parar", "to stop"], ["Partir", "to leave"], ["Pintar", "to paint"], ["Preparar", "to prepare"], 
  ["Procurar", "to look for"], ["Receber", "to receive"], ["Sorrir", "to smile"], ["Tentar", "to try"], ["Tirar", "to take"], 
  ["Tocar", "to play"], ["Usar", "to use"], ["Viajar", "to travel"], ["Visitar", "to visit"], ["Voltar", "to return"], 
  ["Alugar", "to rent"], ["Caminhar", "to walk"], ["Dividir", "to divide"], ["Ensinar", "to teach"], ["Escutar", "to listen"], 
  ["Gastar", "to spend"], ["Ligar", "to call"], ["Organizar", "to organize"], ["Pagar", "to pay"], ["Praticar", "to practice"], 
  ["Prometer", "to promise"], ["Quebrar", "to break"], ["Sonhar", "to dream"], ["Subir", "to climb"], ["Telefonar", "to phone"], 
  ["Vencer", "to win"], ["Acreditar", "to believe"], ["Acordar", "to wake up"], ["Acontecer", "to happen"], ["Agradecer", "to thank"],
  ["Anotar", "to note down"], ["Aparecer", "to appear"]
].forEach(([name, meaning]) => {
  VERB_BANK[name] = makeRegularVerb(name, meaning);
});

export const norm = (s: string) => s.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().trim();