export const PERSON_ORDER = ["Eu", "Tu", "Ele/Ela/Você", "Nós", "Vós", "Eles/Elas/Vocês"];
export const TENSE_ORDER = ["Presente", "Pretérito Perfeito", "Pretérito Imperfeito", "Futuro", "Condicional", "Conjuntivo"];

const FUT_ENDINGS = ["ei", "ás", "á", "emos", "eis", "ão"];
const COND_ENDINGS = ["ia", "ias", "ia", "íamos", "íeis", "iam"];

type Sentences = {
  pres: { pt: string; en: string };
  perf: { pt: string; en: string };
  imp:  { pt: string; en: string };
  fut:  { pt: string; en: string };
  cond: { pt: string; en: string };
  conj: { pt: string; en: string };
};

function makeRegularVerb(infinitive: string, meaning: string, s: Sentences) {
  const lower = infinitive.toLowerCase();
  const ending = lower.slice(-2);
  const stem = lower.slice(0, -2);

  const endings: any = {
    ar: { pres: ["o","as","a","amos","ais","am"], perf: ["ei","aste","ou","amos","astes","aram"], imp: ["ava","avas","ava","ávamos","áveis","avam"], conj: ["e","es","e","emos","eis","em"] },
    er: { pres: ["o","es","e","emos","eis","em"], perf: ["i","este","eu","emos","estes","eram"], imp: ["ia","ias","ia","íamos","íeis","iam"], conj: ["a","as","a","amos","ais","am"] },
    ir: { pres: ["o","es","e","imos","is","em"], perf: ["i","iste","iu","imos","istes","iram"], imp: ["ia","ias","ia","íamos","íeis","iam"], conj: ["a","as","a","amos","ais","am"] }
  };

  const e = endings[ending] || endings.ar;

  return {
    meaning,
    tenses: {
      "Presente":            { forms: PERSON_ORDER.map((_, i) => stem + e.pres[i]), sentence: s.pres },
      "Pretérito Perfeito":  { forms: PERSON_ORDER.map((_, i) => stem + e.perf[i]), sentence: s.perf },
      "Pretérito Imperfeito":{ forms: PERSON_ORDER.map((_, i) => stem + e.imp[i]),  sentence: s.imp  },
      "Futuro":              { forms: PERSON_ORDER.map((_, i) => lower + FUT_ENDINGS[i]), sentence: s.fut  },
      "Condicional":         { forms: PERSON_ORDER.map((_, i) => lower + COND_ENDINGS[i]), sentence: s.cond },
      "Conjuntivo":          { forms: PERSON_ORDER.map((_, i) => stem + e.conj[i]), sentence: s.conj },
    }
  };
}

export const VERB_BANK: any = {
  "Ser":    { meaning: "to be (permanent)", tenses: { "Presente": { forms: ["sou","és","é","somos","sois","são"], sentence: {pt:"Eu sou brasileiro.", en:"I am Brazilian."}}, "Pretérito Perfeito": { forms: ["fui","foste","foi","fomos","fostes","foram"], sentence: {pt:"Eu fui ao Brasil.", en:"I went to Brazil."}}, "Pretérito Imperfeito": { forms: ["era","eras","era","éramos","éreis","eram"], sentence: {pt:"Eu era jovem.", en:"I was young."}}, "Futuro": { forms: ["serei","serás","será","seremos","sereis","serão"], sentence: {pt:"Serei pontual.", en:"I will be punctual."}}, "Condicional": { forms: ["seria","serias","seria","seríamos","seríeis","seriam"], sentence: {pt:"Seria ótimo!", en:"It would be great!"}}, "Conjuntivo": { forms: ["seja","sejas","seja","sejamos","sejais","sejam"], sentence: {pt:"Espero que seja bom.", en:"I hope it's good."}}}},
  "Estar":  { meaning: "to be (temp)", tenses: { "Presente": { forms: ["estou","estás","está","estamos","estais","estão"], sentence: {pt:"Estou em casa.", en:"I'm at home."}}, "Pretérito Perfeito": { forms: ["estive","estiveste","esteve","estivemos","estivestes","estiveram"], sentence: {pt:"Eu estive em Lisboa.", en:"I was in Lisbon."}}, "Pretérito Imperfeito": { forms: ["estava","estavas","estava","estávamos","estáveis","estavam"], sentence: {pt:"Eu estava cansado.", en:"I was tired."}}, "Futuro": { forms: ["estarei","estarás","estará","estaremos","estareis","estarão"], sentence: {pt:"Estarei livre amanhã.", en:"I'll be free tomorrow."}}, "Condicional": { forms: ["estaria","estarias","estaria","estaríamos","estaríeis","estariam"], sentence: {pt:"Eu estaria lá às 9.", en:"I would be there at 9."}}, "Conjuntivo": { forms: ["esteja","estejas","esteja","estejamos","estejais","estejam"], sentence: {pt:"Espero que esteja bem.", en:"I hope you are well."}}}},
  "Ir":     { meaning: "to go", tenses: { "Presente": { forms: ["vou","vais","vai","vamos","ides","vão"], sentence: {pt:"Eu vou ao mercado.", en:"I go to the market."}}, "Pretérito Perfeito": { forms: ["fui","foste","foi","fomos","fostes","foram"], sentence: {pt:"Eu fui ao dentista.", en:"I went to the dentist."}}, "Pretérito Imperfeito": { forms: ["ia","ias","ia","íamos","íeis","iam"], sentence: {pt:"Eu ia à praia no verão.", en:"I used to go to the beach in summer."}}, "Futuro": { forms: ["irei","irás","irá","iremos","ireis","irão"], sentence: {pt:"Irei ao Rio amanhã.", en:"I will go to Rio tomorrow."}}, "Condicional": { forms: ["iria","irias","iria","iríamos","iríeis","iriam"], sentence: {pt:"Eu iria com você.", en:"I would go with you."}}, "Conjuntivo": { forms: ["vá","vás","vá","vamos","vades","vão"], sentence: {pt:"Que tudo vá bem.", en:"May everything go well."}}}},
  "Ter":    { meaning: "to have", tenses: { "Presente": { forms: ["tenho","tens","tem","temos","tendes","têm"], sentence: {pt:"Tenho dois filhos.", en:"I have two children."}}, "Pretérito Perfeito": { forms: ["tive","tiveste","teve","tivemos","tivestes","tiveram"], sentence: {pt:"Tive uma ideia incrível.", en:"I had an incredible idea."}}, "Pretérito Imperfeito": { forms: ["tinha","tinhas","tinha","tínhamos","tínheis","tinham"], sentence: {pt:"Eu tinha um cachorro.", en:"I had a dog."}}, "Futuro": { forms: ["terei","terás","terá","teremos","tereis","terão"], sentence: {pt:"Terei mais tempo na semana.", en:"I'll have more time next week."}}, "Condicional": { forms: ["teria","terias","teria","teríamos","teríeis","teriam"], sentence: {pt:"Teria sido uma boa viagem.", en:"It would've been a good trip."}}, "Conjuntivo": { forms: ["tenha","tenhas","tenha","tenhamos","tenhais","tenham"], sentence: {pt:"Espero que tenha sorte.", en:"I hope you have luck."}}}},
  "Fazer":  { meaning: "to do/make", tenses: { "Presente": { forms: ["faço","fazes","faz","fazemos","fazeis","fazem"], sentence: {pt:"Eu faço café de manhã.", en:"I make coffee in the morning."}}, "Pretérito Perfeito": { forms: ["fiz","fizeste","fez","fizemos","fizestes","fizeram"], sentence: {pt:"Eu fiz as malas ontem.", en:"I packed my bags yesterday."}}, "Pretérito Imperfeito": { forms: ["fazia","fazias","fazia","fazíamos","fazíeis","faziam"], sentence: {pt:"Eu fazia exercício cedo.", en:"I used to exercise early."}}, "Futuro": { forms: ["farei","farás","fará","faremos","fareis","farão"], sentence: {pt:"Farei o jantar hoje.", en:"I'll make dinner today."}}, "Condicional": { forms: ["faria","farias","faria","faríamos","faríeis","fariam"], sentence: {pt:"Eu faria tudo diferente.", en:"I would do everything differently."}}, "Conjuntivo": { forms: ["faça","faças","faça","façamos","façais","façam"], sentence: {pt:"Faça o que precisar.", en:"Do what you need."}}}},
  "Poder":  { meaning: "can/to be able", tenses: { "Presente": { forms: ["posso","podes","pode","podemos","podeis","podem"], sentence: {pt:"Eu posso te ajudar.", en:"I can help you."}}, "Pretérito Perfeito": { forms: ["pude","pudeste","pôde","pudemos","pudestes","puderam"], sentence: {pt:"Não pude comparecer.", en:"I couldn't attend."}}, "Pretérito Imperfeito": { forms: ["podia","podias","podia","podíamos","podíeis","podiam"], sentence: {pt:"Eu podia dormir tarde.", en:"I could sleep in late."}}, "Futuro": { forms: ["poderei","poderás","poderá","poderemos","podereis","poderão"], sentence: {pt:"Poderei viajar no verão.", en:"I'll be able to travel in summer."}}, "Condicional": { forms: ["poderia","poderias","poderia","poderíamos","poderíeis","poderiam"], sentence: {pt:"Eu poderia ligar mais tarde.", en:"I could call later."}}, "Conjuntivo": { forms: ["possa","possas","possa","possamos","possais","possam"], sentence: {pt:"Espero que possa vir.", en:"I hope you can come."}}}},
  "Dizer":  { meaning: "to say", tenses: { "Presente": { forms: ["digo","dizes","diz","dizemos","dizeis","dizem"], sentence: {pt:"Eu digo sempre a verdade.", en:"I always tell the truth."}}, "Pretérito Perfeito": { forms: ["disse","disseste","disse","dissemos","dissestes","disseram"], sentence: {pt:"Eu disse adeus.", en:"I said goodbye."}}, "Pretérito Imperfeito": { forms: ["dizia","dizias","dizia","dizíamos","dizíeis","diziam"], sentence: {pt:"Ela dizia que amava o Brasil.", en:"She used to say she loved Brazil."}}, "Futuro": { forms: ["direi","dirás","dirá","diremos","direis","dirão"], sentence: {pt:"Eu direi o que penso.", en:"I will say what I think."}}, "Condicional": { forms: ["diria","dirias","diria","diríamos","diríeis","diriam"], sentence: {pt:"Eu diria que sim.", en:"I would say yes."}}, "Conjuntivo": { forms: ["diga","digas","diga","digamos","digais","digam"], sentence: {pt:"Diga-me a verdade.", en:"Tell me the truth."}}}},
  "Saber":  { meaning: "to know (facts)", tenses: { "Presente": { forms: ["sei","sabes","sabe","sabemos","sabeis","sabem"], sentence: {pt:"Eu sei falar inglês.", en:"I know how to speak English."}}, "Pretérito Perfeito": { forms: ["soube","soubeste","soube","soubemos","soubestes","souberam"], sentence: {pt:"Eu soube a notícia ontem.", en:"I found out the news yesterday."}}, "Pretérito Imperfeito": { forms: ["sabia","sabias","sabia","sabíamos","sabíeis","sabiam"], sentence: {pt:"Eu sabia a resposta.", en:"I knew the answer."}}, "Futuro": { forms: ["saberei","saberás","saberá","saberemos","sabereis","saberão"], sentence: {pt:"Saberei os resultados amanhã.", en:"I will know the results tomorrow."}}, "Condicional": { forms: ["saberia","saberias","saberia","saberíamos","saberíeis","saberiam"], sentence: {pt:"Eu saberia o caminho.", en:"I would know the way."}}, "Conjuntivo": { forms: ["saiba","saibas","saiba","saibamos","saibais","saibam"], sentence: {pt:"Espero que saiba a resposta.", en:"I hope you know the answer."}}}},
  "Ver":    { meaning: "to see", tenses: { "Presente": { forms: ["vejo","vês","vê","vemos","vedes","veem"], sentence: {pt:"Eu vejo o mar daqui.", en:"I see the sea from here."}}, "Pretérito Perfeito": { forms: ["vi","viste","viu","vimos","vistes","viram"], sentence: {pt:"Eu vi aquele filme.", en:"I saw that film."}}, "Pretérito Imperfeito": { forms: ["via","vias","via","víamos","víeis","viam"], sentence: {pt:"Eu via o pôr do sol.", en:"I used to watch the sunset."}}, "Futuro": { forms: ["verei","verás","verá","veremos","vereis","verão"], sentence: {pt:"Eu verei o jogo amanhã.", en:"I will watch the game tomorrow."}}, "Condicional": { forms: ["veria","verias","veria","veríamos","veríeis","veriam"], sentence: {pt:"Eu veria de novo com prazer.", en:"I would watch it again with pleasure."}}, "Conjuntivo": { forms: ["veja","vejas","veja","vejamos","vejais","vejam"], sentence: {pt:"Veja bem antes de decidir.", en:"Look carefully before deciding."}}}},
  "Dar":    { meaning: "to give", tenses: { "Presente": { forms: ["dou","dás","dá","damos","dais","dão"], sentence: {pt:"Eu dou aulas de português.", en:"I give Portuguese lessons."}}, "Pretérito Perfeito": { forms: ["dei","deste","deu","demos","destes","deram"], sentence: {pt:"Eu dei um presente à minha mãe.", en:"I gave my mother a gift."}}, "Pretérito Imperfeito": { forms: ["dava","davas","dava","dávamos","dáveis","davam"], sentence: {pt:"Eu dava gorjeta sempre.", en:"I always used to give tips."}}, "Futuro": { forms: ["darei","darás","dará","daremos","dareis","darão"], sentence: {pt:"Eu darei uma resposta amanhã.", en:"I will give an answer tomorrow."}}, "Condicional": { forms: ["daria","darias","daria","daríamos","daríeis","dariam"], sentence: {pt:"Eu daria tudo por isso.", en:"I would give everything for it."}}, "Conjuntivo": { forms: ["dê","dês","dê","demos","deis","deem"], sentence: {pt:"Espero que dê certo.", en:"I hope it works out."}}}},
  "Querer": { meaning: "to want", tenses: { "Presente": { forms: ["quero","queres","quer","queremos","quereis","querem"], sentence: {pt:"Quero aprender português.", en:"I want to learn Portuguese."}}, "Pretérito Perfeito": { forms: ["quis","quiseste","quis","quisemos","quisestes","quiseram"], sentence: {pt:"Quis ficar mais tempo.", en:"I wanted to stay longer."}}, "Pretérito Imperfeito": { forms: ["queria","querias","queria","queríamos","queríeis","queriam"], sentence: {pt:"Eu queria ser cantor.", en:"I wanted to be a singer."}}, "Futuro": { forms: ["quererei","quererás","quererá","quereremos","querereis","quererão"], sentence: {pt:"Eu quererei sempre o melhor.", en:"I will always want the best."}}, "Condicional": { forms: ["quereria","quererias","quereria","quereríamos","quereríeis","quereriam"], sentence: {pt:"Eu quereria uma segunda chance.", en:"I would want a second chance."}}, "Conjuntivo": { forms: ["queira","queiras","queira","queiramos","queirais","queiram"], sentence: {pt:"Que faças o que queiras.", en:"Do whatever you want."}}}},
  "Pôr":    { meaning: "to put", tenses: { "Presente": { forms: ["ponho","pões","põe","pomos","pondes","põem"], sentence: {pt:"Eu ponho açúcar no café.", en:"I put sugar in my coffee."}}, "Pretérito Perfeito": { forms: ["pus","puseste","pôs","pusemos","pusestes","puseram"], sentence: {pt:"Eu pus as chaves na mesa.", en:"I put the keys on the table."}}, "Pretérito Imperfeito": { forms: ["punha","punhas","punha","púnhamos","púnheis","punham"], sentence: {pt:"Eu punha a mesa ao jantar.", en:"I used to set the table for dinner."}}, "Futuro": { forms: ["porei","porás","porá","poremos","poreis","porão"], sentence: {pt:"Eu porei tudo em ordem.", en:"I will put everything in order."}}, "Condicional": { forms: ["poria","porias","poria","poríamos","poríeis","poriam"], sentence: {pt:"Eu poria mais sal.", en:"I would put more salt."}}, "Conjuntivo": { forms: ["ponha","ponhas","ponha","ponhamos","ponhais","ponham"], sentence: {pt:"Ponha o casaco, está frio.", en:"Put on your coat, it's cold."}}}},
  "Ler":    { meaning: "to read", tenses: { "Presente": { forms: ["leio","lês","lê","lemos","ledes","leem"], sentence: {pt:"Eu leio o jornal de manhã.", en:"I read the newspaper in the morning."}}, "Pretérito Perfeito": { forms: ["li","leste","leu","lemos","lestes","leram"], sentence: {pt:"Eu li o livro inteiro.", en:"I read the whole book."}}, "Pretérito Imperfeito": { forms: ["lia","lias","lia","líamos","líeis","liam"], sentence: {pt:"Eu lia antes de dormir.", en:"I used to read before sleeping."}}, "Futuro": { forms: ["lerei","lerás","lerá","leremos","lereis","lerão"], sentence: {pt:"Eu lerei esse romance.", en:"I will read that novel."}}, "Condicional": { forms: ["leria","lerias","leria","leríamos","leríeis","leriam"], sentence: {pt:"Eu leria mais se tivesse tempo.", en:"I would read more if I had time."}}, "Conjuntivo": { forms: ["leia","leias","leia","leiamos","leiais","leiam"], sentence: {pt:"Leia as instruções primeiro.", en:"Read the instructions first."}}}},
  "Vir":    { meaning: "to come", tenses: { "Presente": { forms: ["venho","vens","vem","vimos","vindes","vêm"], sentence: {pt:"Venho do trabalho agora.", en:"I'm coming from work now."}}, "Pretérito Perfeito": { forms: ["vim","vieste","veio","viemos","viestes","vieram"], sentence: {pt:"Eu vim de ônibus.", en:"I came by bus."}}, "Pretérito Imperfeito": { forms: ["vinha","vinhas","vinha","vínhamos","vínheis","vinham"], sentence: {pt:"Eu vinha aqui todo sábado.", en:"I used to come here every Saturday."}}, "Futuro": { forms: ["virei","virás","virá","viremos","vireis","virão"], sentence: {pt:"Eu virei te visitar.", en:"I will come visit you."}}, "Condicional": { forms: ["viria","virias","viria","viríamos","viríeis","viriam"], sentence: {pt:"Ele viria se soubesse.", en:"He would come if he knew."}}, "Conjuntivo": { forms: ["venha","venhas","venha","venhamos","venhais","venham"], sentence: {pt:"Venha quando quiser.", en:"Come whenever you want."}}}},
  "Trazer": { meaning: "to bring", tenses: { "Presente": { forms: ["trago","trazes","traz","trazemos","trazeis","trazem"], sentence: {pt:"Eu trago o almoço.", en:"I bring lunch."}}, "Pretérito Perfeito": { forms: ["trouxe","trouxeste","trouxe","trouxemos","trouxestes","trouxeram"], sentence: {pt:"Eu trouxe uma lembrança.", en:"I brought a souvenir."}}, "Pretérito Imperfeito": { forms: ["trazia","trazias","trazia","trazíamos","trazíeis","traziam"], sentence: {pt:"Eu trazia flores para ela.", en:"I used to bring her flowers."}}, "Futuro": { forms: ["trarei","trarás","trará","traremos","trareis","trarão"], sentence: {pt:"Eu trarei o contrato.", en:"I will bring the contract."}}, "Condicional": { forms: ["traria","trarias","traria","traríamos","traríeis","trariam"], sentence: {pt:"Eu traria mais comida.", en:"I would bring more food."}}, "Conjuntivo": { forms: ["traga","tragas","traga","tragamos","tragais","tragam"], sentence: {pt:"Traga o guarda-chuva.", en:"Bring the umbrella."}}}},
  "Ouvir":  { meaning: "to hear", tenses: { "Presente": { forms: ["ouço","ouves","ouve","ouvimos","ouvis","ouvem"], sentence: {pt:"Eu ouço samba de manhã.", en:"I listen to samba in the morning."}}, "Pretérito Perfeito": { forms: ["ouvi","ouviste","ouviu","ouvimos","ouvistes","ouviram"], sentence: {pt:"Eu ouvi a notícia no rádio.", en:"I heard the news on the radio."}}, "Pretérito Imperfeito": { forms: ["ouvia","ouvias","ouvia","ouvíamos","ouvíeis","ouviam"], sentence: {pt:"Eu ouvia vinyl na infância.", en:"I used to listen to vinyl as a child."}}, "Futuro": { forms: ["ouvirei","ouvirás","ouvirá","ouviremos","ouvireis","ouvirão"], sentence: {pt:"Eu ouvirei o podcast.", en:"I will listen to the podcast."}}, "Condicional": { forms: ["ouviria","ouvirias","ouviria","ouviríamos","ouviríeis","ouviriam"], sentence: {pt:"Eu ouviria se estivesse quieto.", en:"I would hear if it were quiet."}}, "Conjuntivo": { forms: ["ouça","ouças","ouça","ouçamos","ouçais","ouçam"], sentence: {pt:"Ouça com atenção.", en:"Listen carefully."}}}},
  "Sair":   { meaning: "to leave", tenses: { "Presente": { forms: ["saio","sais","sai","saímos","saís","saem"], sentence: {pt:"Eu saio às oito.", en:"I leave at eight."}}, "Pretérito Perfeito": { forms: ["saí","saíste","saiu","saímos","saístes","saíram"], sentence: {pt:"Saí sem dizer adeus.", en:"I left without saying goodbye."}}, "Pretérito Imperfeito": { forms: ["saía","saías","saía","saíamos","saíeis","saíam"], sentence: {pt:"Eu saía para correr.", en:"I used to go out for a run."}}, "Futuro": { forms: ["sairei","sairás","sairá","sairemos","saireis","sairão"], sentence: {pt:"Sairei mais cedo hoje.", en:"I will leave earlier today."}}, "Condicional": { forms: ["sairia","sairias","sairia","sairíamos","sairíeis","sairiam"], sentence: {pt:"Eu sairia se não chovesse.", en:"I would go out if it wasn't raining."}}, "Conjuntivo": { forms: ["saia","saias","saia","saiamos","saiais","saiam"], sentence: {pt:"Saia antes que tarde.", en:"Leave before it's too late."}}}},
  "Pedir":  { meaning: "to ask for", tenses: { "Presente": { forms: ["peço","pedes","pede","pedimos","pedis","pedem"], sentence: {pt:"Eu peço a conta.", en:"I ask for the bill."}}, "Pretérito Perfeito": { forms: ["pedi","pediste","pediu","pedimos","pedistes","pediram"], sentence: {pt:"Eu pedi uma pizza.", en:"I ordered a pizza."}}, "Pretérito Imperfeito": { forms: ["pedia","pedias","pedia","pedíamos","pedíeis","pediam"], sentence: {pt:"Eu pedia desculpas sempre.", en:"I always used to apologise."}}, "Futuro": { forms: ["pedirei","pedirás","pedirá","pediremos","pedireis","pedirão"], sentence: {pt:"Pedirei o menu.", en:"I will ask for the menu."}}, "Condicional": { forms: ["pediria","pedirias","pediria","pediríamos","pediríeis","pediriam"], sentence: {pt:"Eu pediria mais tempo.", en:"I would ask for more time."}}, "Conjuntivo": { forms: ["peça","peças","peça","peçamos","peçais","peçam"], sentence: {pt:"Peça quando precisar.", en:"Ask when you need it."}}}}
};

// Unique sentences for all regular verbs
const REGULAR_VERBS: [string, string, Sentences][] = [
  ["Falar",     "to speak",    { pres:{pt:"Eu falo português em casa.",en:"I speak Portuguese at home."}, perf:{pt:"Eu falei com o professor.",en:"I spoke with the teacher."}, imp:{pt:"Eu falava rápido demais.",en:"I used to speak too fast."}, fut:{pt:"Falarei no evento.",en:"I will speak at the event."}, cond:{pt:"Eu falaria mais devagar.",en:"I would speak more slowly."}, conj:{pt:"Espero que fales bem.",en:"I hope you speak well."}}],
  ["Comer",     "to eat",      { pres:{pt:"Eu como fruta todo dia.",en:"I eat fruit every day."}, perf:{pt:"Comi camarão na praia.",en:"I ate shrimp at the beach."}, imp:{pt:"Eu comia churrasco aos domingos.",en:"I used to eat barbecue on Sundays."}, fut:{pt:"Comerei feijoada amanhã.",en:"I will eat feijoada tomorrow."}, cond:{pt:"Eu comeria mais se tivesse fome.",en:"I would eat more if I were hungry."}, conj:{pt:"Espero que coma bem.",en:"I hope you eat well."}}],
  ["Beber",     "to drink",    { pres:{pt:"Eu bebo água com limão.",en:"I drink water with lemon."}, perf:{pt:"Bebi suco de maracujá.",en:"I drank passion fruit juice."}, imp:{pt:"Eu bebia café forte.",en:"I used to drink strong coffee."}, fut:{pt:"Beberei caipirinha na festa.",en:"I will drink caipirinha at the party."}, cond:{pt:"Eu beberia mais água.",en:"I would drink more water."}, conj:{pt:"É importante que beba bastante.",en:"It's important you drink enough."}}],
  ["Trabalhar", "to work",     { pres:{pt:"Eu trabalho num escritório.",en:"I work in an office."}, perf:{pt:"Trabalhei até tarde.",en:"I worked until late."}, imp:{pt:"Eu trabalhava ao ar livre.",en:"I used to work outdoors."}, fut:{pt:"Trabalharei de casa amanhã.",en:"I will work from home tomorrow."}, cond:{pt:"Eu trabalharia mais horas.",en:"I would work more hours."}, conj:{pt:"Espero que trabalhe bem.",en:"I hope you work well."}}],
  ["Estudar",   "to study",    { pres:{pt:"Eu estudo português toda noite.",en:"I study Portuguese every night."}, perf:{pt:"Estudei para o exame.",en:"I studied for the exam."}, imp:{pt:"Eu estudava na biblioteca.",en:"I used to study in the library."}, fut:{pt:"Estudarei gramática amanhã.",en:"I will study grammar tomorrow."}, cond:{pt:"Estudaria mais se pudesse.",en:"I would study more if I could."}, conj:{pt:"É bom que estudes.",en:"It's good that you study."}}],
  ["Morar",     "to live",     { pres:{pt:"Eu moro no Rio de Janeiro.",en:"I live in Rio de Janeiro."}, perf:{pt:"Morei em São Paulo por dois anos.",en:"I lived in São Paulo for two years."}, imp:{pt:"Eu morava perto da praia.",en:"I used to live near the beach."}, fut:{pt:"Morarei no Brasil.",en:"I will live in Brazil."}, cond:{pt:"Eu moraria em Salvador.",en:"I would live in Salvador."}, conj:{pt:"Espero que more bem.",en:"I hope you live well."}}],
  ["Abrir",     "to open",     { pres:{pt:"Eu abro a janela de manhã.",en:"I open the window in the morning."}, perf:{pt:"Abri a porta devagar.",en:"I opened the door slowly."}, imp:{pt:"Eu abria a loja cedo.",en:"I used to open the shop early."}, fut:{pt:"Abrirei uma conta bancária.",en:"I will open a bank account."}, cond:{pt:"Eu abriria um restaurante.",en:"I would open a restaurant."}, conj:{pt:"Espero que abra bem.",en:"I hope it opens well."}}],
  ["Fechar",    "to close",    { pres:{pt:"Eu fecho a porta com cuidado.",en:"I close the door carefully."}, perf:{pt:"Fechei o computador.",en:"I closed the computer."}, imp:{pt:"Eu fechava o negócio às seis.",en:"I used to close the business at six."}, fut:{pt:"Fecharei às dez.",en:"I will close at ten."}, cond:{pt:"Fecharia mais cedo.",en:"I would close earlier."}, conj:{pt:"Espero que feche a tempo.",en:"I hope it closes in time."}}],
  ["Comprar",   "to buy",      { pres:{pt:"Eu compro no mercado local.",en:"I buy at the local market."}, perf:{pt:"Comprei um livro de português.",en:"I bought a Portuguese book."}, imp:{pt:"Eu comprava roupa importada.",en:"I used to buy imported clothes."}, fut:{pt:"Comprarei um carro novo.",en:"I will buy a new car."}, cond:{pt:"Compraria mais se tivesse dinheiro.",en:"I would buy more if I had money."}, conj:{pt:"Espero que compre bem.",en:"I hope you buy wisely."}}],
  ["Vender",    "to sell",     { pres:{pt:"Eu vendo artesanato.",en:"I sell handicrafts."}, perf:{pt:"Vendi a moto ontem.",en:"I sold the motorbike yesterday."}, imp:{pt:"Eu vendia frutas na feira.",en:"I used to sell fruit at the market."}, fut:{pt:"Venderei a casa.",en:"I will sell the house."}, cond:{pt:"Venderia tudo para viajar.",en:"I would sell everything to travel."}, conj:{pt:"Espero que venda rápido.",en:"I hope it sells fast."}}],
  ["Gostar",    "to like",     { pres:{pt:"Eu gosto de música brasileira.",en:"I like Brazilian music."}, perf:{pt:"Gostei muito da comida.",en:"I really liked the food."}, imp:{pt:"Eu gostava de futebol.",en:"I used to like football."}, fut:{pt:"Gostarei da experiência.",en:"I will like the experience."}, cond:{pt:"Gostaria de visitar o Nordeste.",en:"I would like to visit the Northeast."}, conj:{pt:"Espero que gostes.",en:"I hope you like it."}}],
  ["Dormir",    "to sleep",    { pres:{pt:"Eu durmo oito horas.",en:"I sleep eight hours."}, perf:{pt:"Dormi muito bem.",en:"I slept very well."}, imp:{pt:"Eu dormia com a janela aberta.",en:"I used to sleep with the window open."}, fut:{pt:"Dormirei cedo hoje.",en:"I will sleep early today."}, cond:{pt:"Dormiria mais se pudesse.",en:"I would sleep more if I could."}, conj:{pt:"É importante que durmas.",en:"It's important that you sleep."}}],
  ["Correr",    "to run",      { pres:{pt:"Eu corro na praia.",en:"I run on the beach."}, perf:{pt:"Corri cinco quilômetros.",en:"I ran five kilometres."}, imp:{pt:"Eu corria todas as manhãs.",en:"I used to run every morning."}, fut:{pt:"Correrei a maratona.",en:"I will run the marathon."}, cond:{pt:"Correria mais se não chovesse.",en:"I would run more if it didn't rain."}, conj:{pt:"Espero que corra bem.",en:"I hope it goes well."}}],
  ["Andar",     "to walk",     { pres:{pt:"Eu ando de bicicleta.",en:"I ride a bicycle."}, perf:{pt:"Andei pela cidade.",en:"I walked around the city."}, imp:{pt:"Eu andava descalço.",en:"I used to walk barefoot."}, fut:{pt:"Andarei pelo centro histórico.",en:"I will walk through the historic centre."}, cond:{pt:"Andaria mais se tivesse tempo.",en:"I would walk more if I had time."}, conj:{pt:"Espero que ande melhor.",en:"I hope you walk better."}}],
  ["Chegar",    "to arrive",   { pres:{pt:"Eu chego sempre no horário.",en:"I always arrive on time."}, perf:{pt:"Cheguei ao aeroporto.",en:"I arrived at the airport."}, imp:{pt:"Eu chegava atrasado às vezes.",en:"I sometimes used to arrive late."}, fut:{pt:"Chegarei às três.",en:"I will arrive at three."}, cond:{pt:"Chegaria mais cedo.",en:"I would arrive earlier."}, conj:{pt:"Espero que chegue bem.",en:"I hope you arrive safely."}}],
  ["Passar",    "to pass",     { pres:{pt:"Eu passo pelo parque.",en:"I pass through the park."}, perf:{pt:"Passei um mês no Brasil.",en:"I spent a month in Brazil."}, imp:{pt:"Eu passava as férias na praia.",en:"I used to spend holidays at the beach."}, fut:{pt:"Passarei por aí.",en:"I will pass by there."}, cond:{pt:"Passaria mais tempo lá.",en:"I would spend more time there."}, conj:{pt:"Espero que passe bem.",en:"I hope you are well."}}],
  ["Ficar",     "to stay",     { pres:{pt:"Eu fico em casa nos fins de semana.",en:"I stay home on weekends."}, perf:{pt:"Fiquei no hotel.",en:"I stayed at the hotel."}, imp:{pt:"Eu ficava acordado até tarde.",en:"I used to stay up late."}, fut:{pt:"Ficarei mais uma semana.",en:"I will stay one more week."}, cond:{pt:"Ficaria mais tempo.",en:"I would stay longer."}, conj:{pt:"Espero que fique bem.",en:"I hope you get better."}}],
  ["Deixar",    "to leave",    { pres:{pt:"Eu deixo a chave na porta.",en:"I leave the key at the door."}, perf:{pt:"Deixei o casaco no carro.",en:"I left my jacket in the car."}, imp:{pt:"Eu deixava bilhetes.",en:"I used to leave notes."}, fut:{pt:"Deixarei um recado.",en:"I will leave a message."}, cond:{pt:"Deixaria mais espaço.",en:"I would leave more space."}, conj:{pt:"Deixe que eu ajudo.",en:"Let me help."}}],
  ["Achar",     "to think",    { pres:{pt:"Eu acho que vai chover.",en:"I think it's going to rain."}, perf:{pt:"Achei a resposta certa.",en:"I found the right answer."}, imp:{pt:"Eu achava que era fácil.",en:"I used to think it was easy."}, fut:{pt:"Acharei a solução.",en:"I will find the solution."}, cond:{pt:"Acharia melhor esperar.",en:"I would think it's better to wait."}, conj:{pt:"Espero que ache o caminho.",en:"I hope you find the way."}}],
  ["Pensar",    "to think",    { pres:{pt:"Eu penso antes de agir.",en:"I think before acting."}, perf:{pt:"Pensei muito sobre isso.",en:"I thought a lot about it."}, imp:{pt:"Eu pensava diferente.",en:"I used to think differently."}, fut:{pt:"Pensarei em tudo.",en:"I will think about everything."}, cond:{pt:"Pensaria duas vezes.",en:"I would think twice."}, conj:{pt:"É bom que penses.",en:"It's good that you think."}}],
  ["Precisar",  "to need",     { pres:{pt:"Eu preciso de ajuda.",en:"I need help."}, perf:{pt:"Precisei de um médico.",en:"I needed a doctor."}, imp:{pt:"Eu precisava de mais tempo.",en:"I used to need more time."}, fut:{pt:"Precisarei de um passaporte.",en:"I will need a passport."}, cond:{pt:"Precisaria de mais informação.",en:"I would need more information."}, conj:{pt:"Espero que não precise.",en:"I hope you don't need it."}}],
  ["Amar",      "to love",     { pres:{pt:"Eu amo o Brasil.",en:"I love Brazil."}, perf:{pt:"Amei cada momento.",en:"I loved every moment."}, imp:{pt:"Eu amava a cultura local.",en:"I used to love the local culture."}, fut:{pt:"Amarei sempre a língua.",en:"I will always love the language."}, cond:{pt:"Amaria morar aqui.",en:"I would love to live here."}, conj:{pt:"Espero que ames a viagem.",en:"I hope you love the trip."}}],
  ["Chamar",    "to call",     { pres:{pt:"Eu chamo o táxi.",en:"I call a taxi."}, perf:{pt:"Chamei o garçom.",en:"I called the waiter."}, imp:{pt:"Eu chamava pelo nome.",en:"I used to call by name."}, fut:{pt:"Chamarei você amanhã.",en:"I will call you tomorrow."}, cond:{pt:"Chamaria um amigo.",en:"I would call a friend."}, conj:{pt:"Chame-me quando chegar.",en:"Call me when you arrive."}}],
  ["Olhar",     "to look",     { pres:{pt:"Eu olho o horizonte.",en:"I look at the horizon."}, perf:{pt:"Olhei o mapa.",en:"I looked at the map."}, imp:{pt:"Eu olhava as estrelas.",en:"I used to look at the stars."}, fut:{pt:"Olharei os detalhes.",en:"I will look at the details."}, cond:{pt:"Olharia de outro ângulo.",en:"I would look from another angle."}, conj:{pt:"Olhe bem antes de ir.",en:"Look carefully before going."}}],
  ["Escrever",  "to write",    { pres:{pt:"Eu escrevo cartas.",en:"I write letters."}, perf:{pt:"Escrevi um poema.",en:"I wrote a poem."}, imp:{pt:"Eu escrevia no diário.",en:"I used to write in my diary."}, fut:{pt:"Escreverei um livro.",en:"I will write a book."}, cond:{pt:"Escreveria mais.",en:"I would write more."}, conj:{pt:"Espero que escreva bem.",en:"I hope you write well."}}],
  ["Responder", "to answer",   { pres:{pt:"Eu respondo os emails.",en:"I answer emails."}, perf:{pt:"Respondi a pergunta.",en:"I answered the question."}, imp:{pt:"Eu respondia rapidamente.",en:"I used to answer quickly."}, fut:{pt:"Responderei amanhã.",en:"I will answer tomorrow."}, cond:{pt:"Responderia se soubesse.",en:"I would answer if I knew."}, conj:{pt:"Espero que responda logo.",en:"I hope you answer soon."}}],
  ["Entrar",    "to enter",    { pres:{pt:"Eu entro pelo portão.",en:"I enter through the gate."}, perf:{pt:"Entrei na universidade.",en:"I entered university."}, imp:{pt:"Eu entrava sem bater.",en:"I used to enter without knocking."}, fut:{pt:"Entrarei no clube.",en:"I will enter the club."}, cond:{pt:"Entraria se pudesse.",en:"I would enter if I could."}, conj:{pt:"Entre, por favor.",en:"Please come in."}}],
  ["Ajudar",    "to help",     { pres:{pt:"Eu ajudo os colegas.",en:"I help my colleagues."}, perf:{pt:"Ajudei na mudança.",en:"I helped with the move."}, imp:{pt:"Eu ajudava no voluntariado.",en:"I used to help with volunteering."}, fut:{pt:"Ajudarei quando precisar.",en:"I will help when needed."}, cond:{pt:"Ajudaria mais.",en:"I would help more."}, conj:{pt:"Espero que ajude.",en:"I hope you help."}}],
  ["Aprender",  "to learn",    { pres:{pt:"Eu aprendo algo novo todo dia.",en:"I learn something new every day."}, perf:{pt:"Aprendi a cozinhar.",en:"I learned to cook."}, imp:{pt:"Eu aprendia tocando violão.",en:"I used to learn by playing guitar."}, fut:{pt:"Aprenderei espanhol.",en:"I will learn Spanish."}, cond:{pt:"Aprenderia mais rápido com prática.",en:"I would learn faster with practice."}, conj:{pt:"Espero que aprenda logo.",en:"I hope you learn quickly."}}],
  ["Assistir",  "to watch",    { pres:{pt:"Eu assisto ao noticiário.",en:"I watch the news."}, perf:{pt:"Assisti a um documentário.",en:"I watched a documentary."}, imp:{pt:"Eu assistia novela à noite.",en:"I used to watch soap operas at night."}, fut:{pt:"Assistirei ao jogo.",en:"I will watch the game."}, cond:{pt:"Assistiria ao concerto.",en:"I would watch the concert."}, conj:{pt:"Espero que assista.",en:"I hope you watch it."}}],
  ["Cantar",    "to sing",     { pres:{pt:"Eu canto no carro.",en:"I sing in the car."}, perf:{pt:"Cantei no coral.",en:"I sang in the choir."}, imp:{pt:"Eu cantava na escola.",en:"I used to sing at school."}, fut:{pt:"Cantarei no palco.",en:"I will sing on stage."}, cond:{pt:"Cantaria mais alto.",en:"I would sing louder."}, conj:{pt:"Espero que cante bem.",en:"I hope you sing well."}}],
  ["Cozinhar",  "to cook",     { pres:{pt:"Eu cozinho feijão.",en:"I cook beans."}, perf:{pt:"Cozinhei para vinte pessoas.",en:"I cooked for twenty people."}, imp:{pt:"Eu cozinhava sem receita.",en:"I used to cook without a recipe."}, fut:{pt:"Cozinharei o frango.",en:"I will cook the chicken."}, cond:{pt:"Cozinharia mais se tivesse tempo.",en:"I would cook more if I had time."}, conj:{pt:"Espero que cozinhe bem.",en:"I hope you cook well."}}],
  ["Dançar",    "to dance",    { pres:{pt:"Eu danço samba.",en:"I dance samba."}, perf:{pt:"Dancei a noite toda.",en:"I danced all night."}, imp:{pt:"Eu dançava forró.",en:"I used to dance forró."}, fut:{pt:"Dançarei no carnaval.",en:"I will dance at carnival."}, cond:{pt:"Dançaria se soubesse.",en:"I would dance if I knew how."}, conj:{pt:"Espero que dance comigo.",en:"I hope you dance with me."}}],
  ["Decidir",   "to decide",   { pres:{pt:"Eu decido rápido.",en:"I decide quickly."}, perf:{pt:"Decidi ficar.",en:"I decided to stay."}, imp:{pt:"Eu decidia com calma.",en:"I used to decide calmly."}, fut:{pt:"Decidirei logo.",en:"I will decide soon."}, cond:{pt:"Decidiria de outra forma.",en:"I would decide differently."}, conj:{pt:"Espero que decida bem.",en:"I hope you decide well."}}],
  ["Descansar", "to rest",     { pres:{pt:"Eu descanso depois do trabalho.",en:"I rest after work."}, perf:{pt:"Descansei no fim de semana.",en:"I rested over the weekend."}, imp:{pt:"Eu descansava na rede.",en:"I used to rest in the hammock."}, fut:{pt:"Descansarei nas férias.",en:"I will rest on holiday."}, cond:{pt:"Descansaria mais.",en:"I would rest more."}, conj:{pt:"Descanse um pouco.",en:"Rest a little."}}],
  ["Desenhar",  "to draw",     { pres:{pt:"Eu desenho paisagens.",en:"I draw landscapes."}, perf:{pt:"Desenhei o rosto dela.",en:"I drew her face."}, imp:{pt:"Eu desenhava mapas.",en:"I used to draw maps."}, fut:{pt:"Desenharei o plano.",en:"I will draw the plan."}, cond:{pt:"Desenharia melhor com treino.",en:"I would draw better with practice."}, conj:{pt:"Espero que desenhe bem.",en:"I hope you draw well."}}],
  ["Dirigir",   "to drive",    { pres:{pt:"Eu dirijo com cuidado.",en:"I drive carefully."}, perf:{pt:"Dirigi até Salvador.",en:"I drove to Salvador."}, imp:{pt:"Eu dirigia à noite.",en:"I used to drive at night."}, fut:{pt:"Dirigirei o caminhão.",en:"I will drive the truck."}, cond:{pt:"Dirigiria se tivesse carro.",en:"I would drive if I had a car."}, conj:{pt:"Espero que dirija bem.",en:"I hope you drive well."}}],
  ["Escolher",  "to choose",   { pres:{pt:"Eu escolho com cuidado.",en:"I choose carefully."}, perf:{pt:"Escolhi o melhor caminho.",en:"I chose the best path."}, imp:{pt:"Eu escolhia pela qualidade.",en:"I used to choose by quality."}, fut:{pt:"Escolherei a próxima viagem.",en:"I will choose the next trip."}, cond:{pt:"Escolheria diferente.",en:"I would choose differently."}, conj:{pt:"Espero que escolha bem.",en:"I hope you choose well."}}],
  ["Esperar",   "to wait",     { pres:{pt:"Eu espero na fila.",en:"I wait in the queue."}, perf:{pt:"Esperei uma hora.",en:"I waited an hour."}, imp:{pt:"Eu esperava na paragem.",en:"I used to wait at the bus stop."}, fut:{pt:"Esperarei você.",en:"I will wait for you."}, cond:{pt:"Esperaria mais.",en:"I would wait longer."}, conj:{pt:"Espere um momento.",en:"Wait a moment."}}],
  ["Esquecer",  "to forget",   { pres:{pt:"Eu esqueço o guarda-chuva.",en:"I forget my umbrella."}, perf:{pt:"Esqueci o aniversário.",en:"I forgot the birthday."}, imp:{pt:"Eu esquecia os nomes.",en:"I used to forget names."}, fut:{pt:"Não esquecerei esta viagem.",en:"I will not forget this trip."}, cond:{pt:"Esqueceria sem a lista.",en:"I would forget without the list."}, conj:{pt:"Espero que não esqueça.",en:"I hope you don't forget."}}],
  ["Ganhar",    "to win",      { pres:{pt:"Eu ganho bem.",en:"I earn well."}, perf:{pt:"Ganhei o primeiro lugar.",en:"I won first place."}, imp:{pt:"Eu ganhava um salário mínimo.",en:"I used to earn minimum wage."}, fut:{pt:"Ganharei o prêmio.",en:"I will win the prize."}, cond:{pt:"Ganharia mais com experiência.",en:"I would earn more with experience."}, conj:{pt:"Espero que ganhe.",en:"I hope you win."}}],
  ["Lavar",     "to wash",     { pres:{pt:"Eu lavo o carro.",en:"I wash the car."}, perf:{pt:"Lavei a roupa.",en:"I washed the clothes."}, imp:{pt:"Eu lavava à mão.",en:"I used to wash by hand."}, fut:{pt:"Lavarei o banheiro.",en:"I will clean the bathroom."}, cond:{pt:"Lavaria mais vezes.",en:"I would wash more often."}, conj:{pt:"Lave antes de usar.",en:"Wash before using."}}],
  ["Limpar",    "to clean",    { pres:{pt:"Eu limpo a casa.",en:"I clean the house."}, perf:{pt:"Limpei o quarto.",en:"I cleaned the room."}, imp:{pt:"Eu limpava todo sábado.",en:"I used to clean every Saturday."}, fut:{pt:"Limparei o escritório.",en:"I will clean the office."}, cond:{pt:"Limparia mais se tivesse tempo.",en:"I would clean more if I had time."}, conj:{pt:"Limpe antes de sair.",en:"Clean before leaving."}}],
  ["Mandar",    "to send",     { pres:{pt:"Eu mando mensagens.",en:"I send messages."}, perf:{pt:"Mandei um email.",en:"I sent an email."}, imp:{pt:"Eu mandava cartas.",en:"I used to send letters."}, fut:{pt:"Mandarei o documento.",en:"I will send the document."}, cond:{pt:"Mandaria um presente.",en:"I would send a gift."}, conj:{pt:"Mande quando puder.",en:"Send it when you can."}}],
  ["Mudar",     "to change",   { pres:{pt:"Eu mudo de opinião às vezes.",en:"I change my mind sometimes."}, perf:{pt:"Mudei de cidade.",en:"I moved to another city."}, imp:{pt:"Eu mudava de emprego.",en:"I used to change jobs."}, fut:{pt:"Mudarei os planos.",en:"I will change the plans."}, cond:{pt:"Mudaria algo.",en:"I would change something."}, conj:{pt:"Espero que mude para melhor.",en:"I hope it changes for the better."}}],
  ["Nadar",     "to swim",     { pres:{pt:"Eu nado no oceano.",en:"I swim in the ocean."}, perf:{pt:"Nadei em Búzios.",en:"I swam in Búzios."}, imp:{pt:"Eu nadava na lagoa.",en:"I used to swim in the lagoon."}, fut:{pt:"Nadarei amanhã cedo.",en:"I will swim early tomorrow."}, cond:{pt:"Nadaria mais se soubesse.",en:"I would swim more if I knew how."}, conj:{pt:"Espero que nade bem.",en:"I hope you swim well."}}],
  ["Parar",     "to stop",     { pres:{pt:"Eu paro aqui.",en:"I stop here."}, perf:{pt:"Parei de fumar.",en:"I stopped smoking."}, imp:{pt:"Eu parava para descansar.",en:"I used to stop to rest."}, fut:{pt:"Pararei mais cedo.",en:"I will stop earlier."}, cond:{pt:"Pararia se pedissem.",en:"I would stop if asked."}, conj:{pt:"Pare quando quiser.",en:"Stop when you want."}}],
  ["Partir",    "to leave",    { pres:{pt:"Eu parto de manhã.",en:"I leave in the morning."}, perf:{pt:"Parti sem despedida.",en:"I left without saying goodbye."}, imp:{pt:"Eu partia com o amanhecer.",en:"I used to leave at dawn."}, fut:{pt:"Partirei na sexta.",en:"I will leave on Friday."}, cond:{pt:"Partiria mais cedo.",en:"I would leave earlier."}, conj:{pt:"Parta com cuidado.",en:"Leave carefully."}}],
  ["Pintar",    "to paint",    { pres:{pt:"Eu pinto aquarelas.",en:"I paint watercolours."}, perf:{pt:"Pintei o quarto de azul.",en:"I painted the room blue."}, imp:{pt:"Eu pintava nas férias.",en:"I used to paint on holidays."}, fut:{pt:"Pintarei um quadro.",en:"I will paint a picture."}, cond:{pt:"Pintaria mais.",en:"I would paint more."}, conj:{pt:"Espero que pinte bem.",en:"I hope you paint well."}}],
  ["Preparar",  "to prepare",  { pres:{pt:"Eu preparo o almoço.",en:"I prepare lunch."}, perf:{pt:"Preparei a apresentação.",en:"I prepared the presentation."}, imp:{pt:"Eu preparava tudo com antecedência.",en:"I used to prepare everything in advance."}, fut:{pt:"Prepararei a reunião.",en:"I will prepare the meeting."}, cond:{pt:"Prepararia mais.",en:"I would prepare more."}, conj:{pt:"Prepare-se para a entrevista.",en:"Prepare for the interview."}}],
  ["Procurar",  "to look for", { pres:{pt:"Eu procuro trabalho.",en:"I look for work."}, perf:{pt:"Procurei as chaves.",en:"I looked for the keys."}, imp:{pt:"Eu procurava pechinchas.",en:"I used to look for bargains."}, fut:{pt:"Procurarei um apartamento.",en:"I will look for an apartment."}, cond:{pt:"Procuraria outra solução.",en:"I would look for another solution."}, conj:{pt:"Procure com calma.",en:"Look calmly."}}],
  ["Receber",   "to receive",  { pres:{pt:"Eu recebo visitas.",en:"I receive visitors."}, perf:{pt:"Recebi uma boa notícia.",en:"I received good news."}, imp:{pt:"Eu recebia encomendas.",en:"I used to receive packages."}, fut:{pt:"Receberei o resultado.",en:"I will receive the result."}, cond:{pt:"Receberia com prazer.",en:"I would receive with pleasure."}, conj:{pt:"Espero que receba bem.",en:"I hope you receive it well."}}],
  ["Sorrir",    "to smile",    { pres:{pt:"Eu sorrio para as fotos.",en:"I smile for photos."}, perf:{pt:"Sorri quando ouvi a notícia.",en:"I smiled when I heard the news."}, imp:{pt:"Eu sorria sempre.",en:"I always used to smile."}, fut:{pt:"Sorrirei para você.",en:"I will smile at you."}, cond:{pt:"Sorriria mais.",en:"I would smile more."}, conj:{pt:"Sorria, você está no Brasil!",en:"Smile, you're in Brazil!"}}],
  ["Tentar",    "to try",      { pres:{pt:"Eu tento de novo.",en:"I try again."}, perf:{pt:"Tentei muito.",en:"I tried hard."}, imp:{pt:"Eu tentava todo dia.",en:"I used to try every day."}, fut:{pt:"Tentarei outra vez.",en:"I will try again."}, cond:{pt:"Tentaria diferente.",en:"I would try differently."}, conj:{pt:"Tente mais uma vez.",en:"Try one more time."}}],
  ["Tirar",     "to take",     { pres:{pt:"Eu tiro fotos.",en:"I take photos."}, perf:{pt:"Tirei uma foto linda.",en:"I took a beautiful photo."}, imp:{pt:"Eu tirava dúvidas.",en:"I used to clear up doubts."}, fut:{pt:"Tirarei férias.",en:"I will take a holiday."}, cond:{pt:"Tiraria mais fotos.",en:"I would take more photos."}, conj:{pt:"Tire um tempo para você.",en:"Take some time for yourself."}}],
  ["Tocar",     "to play",     { pres:{pt:"Eu toco violão.",en:"I play the guitar."}, perf:{pt:"Toquei na banda.",en:"I played in the band."}, imp:{pt:"Eu tocava piano.",en:"I used to play piano."}, fut:{pt:"Tocarei na festa.",en:"I will play at the party."}, cond:{pt:"Tocaria melhor com prática.",en:"I would play better with practice."}, conj:{pt:"Espero que toque bem.",en:"I hope you play well."}}],
  ["Usar",      "to use",      { pres:{pt:"Eu uso o transporte público.",en:"I use public transport."}, perf:{pt:"Usei o mapa.",en:"I used the map."}, imp:{pt:"Eu usava dicionário.",en:"I used to use a dictionary."}, fut:{pt:"Usarei o aplicativo.",en:"I will use the app."}, cond:{pt:"Usaria mais vezes.",en:"I would use it more often."}, conj:{pt:"Use o que precisar.",en:"Use what you need."}}],
  ["Viajar",    "to travel",   { pres:{pt:"Eu viajo todo ano.",en:"I travel every year."}, perf:{pt:"Viajei de trem.",en:"I travelled by train."}, imp:{pt:"Eu viajava de mochila.",en:"I used to backpack."}, fut:{pt:"Viajarei para o Nordeste.",en:"I will travel to the Northeast."}, cond:{pt:"Viajaria mais se pudesse.",en:"I would travel more if I could."}, conj:{pt:"Espero que viaje bem.",en:"I hope you travel well."}}],
  ["Visitar",   "to visit",    { pres:{pt:"Eu visito museus.",en:"I visit museums."}, perf:{pt:"Visitei o Cristo Redentor.",en:"I visited Christ the Redeemer."}, imp:{pt:"Eu visitava os avós.",en:"I used to visit my grandparents."}, fut:{pt:"Visitarei Salvador.",en:"I will visit Salvador."}, cond:{pt:"Visitaria a Amazónia.",en:"I would visit the Amazon."}, conj:{pt:"Visite quando puder.",en:"Visit when you can."}}],
  ["Voltar",    "to return",   { pres:{pt:"Eu volto para casa às seis.",en:"I return home at six."}, perf:{pt:"Voltei da viagem.",en:"I returned from the trip."}, imp:{pt:"Eu voltava sempre.",en:"I always used to return."}, fut:{pt:"Voltarei ao Brasil.",en:"I will return to Brazil."}, cond:{pt:"Voltaria com prazer.",en:"I would return with pleasure."}, conj:{pt:"Volte logo.",en:"Come back soon."}}],
  ["Alugar",    "to rent",     { pres:{pt:"Eu alugo um quarto.",en:"I rent a room."}, perf:{pt:"Aluguei um carro.",en:"I rented a car."}, imp:{pt:"Eu alugava apartamento.",en:"I used to rent an apartment."}, fut:{pt:"Alugarei uma casa.",en:"I will rent a house."}, cond:{pt:"Alugaria uma villa.",en:"I would rent a villa."}, conj:{pt:"Alugue antes que acabe.",en:"Rent before it runs out."}}],
  ["Caminhar",  "to walk",     { pres:{pt:"Eu caminho pela cidade.",en:"I walk through the city."}, perf:{pt:"Caminhei até a praia.",en:"I walked to the beach."}, imp:{pt:"Eu caminhava pelo parque.",en:"I used to walk through the park."}, fut:{pt:"Caminhare pelo centro.",en:"I will walk through the centre."}, cond:{pt:"Caminharia mais.",en:"I would walk more."}, conj:{pt:"Caminhe devagar.",en:"Walk slowly."}}],
  ["Dividir",   "to divide",   { pres:{pt:"Eu divido a conta.",en:"I split the bill."}, perf:{pt:"Dividi o quarto.",en:"I shared the room."}, imp:{pt:"Eu dividia tudo com ela.",en:"I used to share everything with her."}, fut:{pt:"Dividirei os custos.",en:"I will divide the costs."}, cond:{pt:"Dividiria igualmente.",en:"I would divide equally."}, conj:{pt:"Divida com os colegas.",en:"Share with your colleagues."}}],
  ["Ensinar",   "to teach",    { pres:{pt:"Eu ensino português.",en:"I teach Portuguese."}, perf:{pt:"Ensinei a nadar.",en:"I taught how to swim."}, imp:{pt:"Eu ensinava matemática.",en:"I used to teach maths."}, fut:{pt:"Ensinarei o próximo nível.",en:"I will teach the next level."}, cond:{pt:"Ensinaria de outra forma.",en:"I would teach differently."}, conj:{pt:"Espero que ensine bem.",en:"I hope you teach well."}}],
  ["Escutar",   "to listen",   { pres:{pt:"Eu escuto os podcasts.",en:"I listen to podcasts."}, perf:{pt:"Escutei um conselho.",en:"I listened to some advice."}, imp:{pt:"Eu escutava jazz.",en:"I used to listen to jazz."}, fut:{pt:"Escutarei com atenção.",en:"I will listen carefully."}, cond:{pt:"Escutaria de novo.",en:"I would listen again."}, conj:{pt:"Escute antes de falar.",en:"Listen before speaking."}}],
  ["Gastar",    "to spend",    { pres:{pt:"Eu gasto pouco.",en:"I spend little."}, perf:{pt:"Gastei na viagem.",en:"I spent money on the trip."}, imp:{pt:"Eu gastava em livros.",en:"I used to spend on books."}, fut:{pt:"Gastarei com cuidado.",en:"I will spend carefully."}, cond:{pt:"Gastaria em experiências.",en:"I would spend on experiences."}, conj:{pt:"Não gaste tudo.",en:"Don't spend everything."}}],
  ["Ligar",     "to call",     { pres:{pt:"Eu ligo para a família.",en:"I call my family."}, perf:{pt:"Liguei para o médico.",en:"I called the doctor."}, imp:{pt:"Eu ligava toda semana.",en:"I used to call every week."}, fut:{pt:"Ligarei amanhã cedo.",en:"I will call early tomorrow."}, cond:{pt:"Ligaria se tivesse tempo.",en:"I would call if I had time."}, conj:{pt:"Ligue quando chegar.",en:"Call when you arrive."}}],
  ["Organizar", "to organize", { pres:{pt:"Eu organizo a agenda.",en:"I organise my schedule."}, perf:{pt:"Organizei o evento.",en:"I organised the event."}, imp:{pt:"Eu organizava as viagens.",en:"I used to organise trips."}, fut:{pt:"Organizarei a festa.",en:"I will organise the party."}, cond:{pt:"Organizaria melhor.",en:"I would organise better."}, conj:{pt:"Organize antes de sair.",en:"Organise before leaving."}}],
  ["Pagar",     "to pay",      { pres:{pt:"Eu pago com cartão.",en:"I pay by card."}, perf:{pt:"Paguei a conta.",en:"I paid the bill."}, imp:{pt:"Eu pagava em dinheiro.",en:"I used to pay in cash."}, fut:{pt:"Pagarei quando puder.",en:"I will pay when I can."}, cond:{pt:"Pagaria mais pela qualidade.",en:"I would pay more for quality."}, conj:{pt:"Pague antes de sair.",en:"Pay before leaving."}}],
  ["Praticar",  "to practice", { pres:{pt:"Eu practico surf.",en:"I practice surfing."}, perf:{pt:"Pratiquei natação.",en:"I practiced swimming."}, imp:{pt:"Eu praticava capoeira.",en:"I used to practice capoeira."}, fut:{pt:"Praticarei mais.",en:"I will practice more."}, cond:{pt:"Praticaria todos os dias.",en:"I would practice every day."}, conj:{pt:"Pratique para melhorar.",en:"Practice to improve."}}],
  ["Prometer",  "to promise",  { pres:{pt:"Eu prometo ser honesto.",en:"I promise to be honest."}, perf:{pt:"Prometi voltar.",en:"I promised to return."}, imp:{pt:"Eu prometia e cumpria.",en:"I used to promise and deliver."}, fut:{pt:"Prometerei cuidar.",en:"I will promise to take care."}, cond:{pt:"Prometeria se pudesse.",en:"I would promise if I could."}, conj:{pt:"Prometa que volta.",en:"Promise you'll come back."}}],
  ["Quebrar",   "to break",    { pres:{pt:"Eu quebro recordes.",en:"I break records."}, perf:{pt:"Quebrei o copo.",en:"I broke the glass."}, imp:{pt:"Eu quebrava regras às vezes.",en:"I used to break rules sometimes."}, fut:{pt:"Quebrarei o recorde.",en:"I will break the record."}, cond:{pt:"Quebraria o silêncio.",en:"I would break the silence."}, conj:{pt:"Espero que não quebre.",en:"I hope it doesn't break."}}],
  ["Sonhar",    "to dream",    { pres:{pt:"Eu sonho com o Brasil.",en:"I dream about Brazil."}, perf:{pt:"Sonhei com a praia.",en:"I dreamed about the beach."}, imp:{pt:"Eu sonhava em ser músico.",en:"I used to dream of being a musician."}, fut:{pt:"Sonharei grande.",en:"I will dream big."}, cond:{pt:"Sonharia com viagens.",en:"I would dream about travels."}, conj:{pt:"Sonhe sempre.",en:"Always dream."}}],
  ["Subir",     "to climb",    { pres:{pt:"Eu subo a colina.",en:"I climb the hill."}, perf:{pt:"Subi o Pão de Açúcar.",en:"I climbed Sugar Loaf Mountain."}, imp:{pt:"Eu subia de táxi.",en:"I used to go up by taxi."}, fut:{pt:"Subirei pela trilha.",en:"I will climb by the trail."}, cond:{pt:"Subiria de teleférico.",en:"I would go up by cable car."}, conj:{pt:"Suba com cuidado.",en:"Climb carefully."}}],
  ["Telefonar", "to phone",    { pres:{pt:"Eu telefono à noite.",en:"I phone at night."}, perf:{pt:"Telefonei para o hotel.",en:"I phoned the hotel."}, imp:{pt:"Eu telefonava todo sábado.",en:"I used to phone every Saturday."}, fut:{pt:"Telefonarei amanhã.",en:"I will phone tomorrow."}, cond:{pt:"Telefonaria mas não tinha número.",en:"I would phone but had no number."}, conj:{pt:"Telefone quando chegar.",en:"Phone when you arrive."}}],
  ["Vencer",    "to win",      { pres:{pt:"Eu vences desafios.",en:"I overcome challenges."}, perf:{pt:"Vencemos o jogo.",en:"We won the game."}, imp:{pt:"Eu vencia sempre.",en:"I used to always win."}, fut:{pt:"Vencerei o obstáculo.",en:"I will overcome the obstacle."}, cond:{pt:"Venceria com mais treino.",en:"I would win with more training."}, conj:{pt:"Espero que vença.",en:"I hope you win."}}],
  ["Acreditar", "to believe",  { pres:{pt:"Eu acredito em você.",en:"I believe in you."}, perf:{pt:"Acreditei na promessa.",en:"I believed the promise."}, imp:{pt:"Eu acreditava em milagres.",en:"I used to believe in miracles."}, fut:{pt:"Acreditarei sempre.",en:"I will always believe."}, cond:{pt:"Acreditaria com provas.",en:"I would believe with proof."}, conj:{pt:"Acredite em si mesmo.",en:"Believe in yourself."}}],
  ["Acordar",   "to wake up",  { pres:{pt:"Eu acordo às seis.",en:"I wake up at six."}, perf:{pt:"Acordei com o barulho.",en:"I woke up with the noise."}, imp:{pt:"Eu acordava com o galo.",en:"I used to wake up with the rooster."}, fut:{pt:"Acordarei cedo amanhã.",en:"I will wake up early tomorrow."}, cond:{pt:"Acordaria mais tarde.",en:"I would wake up later."}, conj:{pt:"Acorde antes das oito.",en:"Wake up before eight."}}],
  ["Acontecer", "to happen",   { pres:{pt:"Isso acontece sempre.",en:"This always happens."}, perf:{pt:"Aconteceu algo incrível.",en:"Something incredible happened."}, imp:{pt:"Isso acontecia muito.",en:"This used to happen a lot."}, fut:{pt:"Vai acontecer de novo.",en:"It will happen again."}, cond:{pt:"Aconteceria de qualquer jeito.",en:"It would happen anyway."}, conj:{pt:"Espero que aconteça bem.",en:"I hope it goes well."}}],
  ["Agradecer", "to thank",    { pres:{pt:"Eu agradeço a hospitalidade.",en:"I thank the hospitality."}, perf:{pt:"Agradeci pelo presente.",en:"I thanked for the gift."}, imp:{pt:"Eu agradecia sempre.",en:"I always used to say thank you."}, fut:{pt:"Agradecerei a ajuda.",en:"I will thank you for the help."}, cond:{pt:"Agradeceria de coração.",en:"I would thank sincerely."}, conj:{pt:"Agradeça quando puder.",en:"Thank when you can."}}],
  ["Anotar",    "to note down",{ pres:{pt:"Eu anoto o vocabulário.",en:"I note down vocabulary."}, perf:{pt:"Anotei o endereço.",en:"I noted down the address."}, imp:{pt:"Eu anotava tudo.",en:"I used to note everything down."}, fut:{pt:"Anotarei as instruções.",en:"I will note down the instructions."}, cond:{pt:"Anotaria mais.",en:"I would note down more."}, conj:{pt:"Anote antes de esquecer.",en:"Note it down before you forget."}}],
  ["Aparecer",  "to appear",   { pres:{pt:"Ele aparece de surpresa.",en:"He appears by surprise."}, perf:{pt:"Apareceu uma oportunidade.",en:"An opportunity appeared."}, imp:{pt:"Ela aparecia às vezes.",en:"She used to appear sometimes."}, fut:{pt:"Aparecerá no momento certo.",en:"It will appear at the right time."}, cond:{pt:"Apareceria se convidassem.",en:"I would appear if invited."}, conj:{pt:"Espero que apareça.",en:"I hope it appears."}}],
];

REGULAR_VERBS.forEach(([name, meaning, sentences]) => {
  VERB_BANK[name] = makeRegularVerb(name, meaning, sentences);
});

export const norm = (s: string) => s.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().trim();
